development:
  GOOGLE_CLIENT_ID: 957169596408-jr3nngcfpqq31dhrddopdtf7j3v81a04.apps.googleusercontent.com
  GOOGLE_SECRET_KEY: O6OWmODzF1WFZ4Wb9xZE5_L1

production:
  GOOGLE_CLIENT_ID: 754802324470-f341bt2mmp7lthm56rftbc3gua304ctr.apps.googleusercontent.com
  GOOGLE_SECRET_KEY: -SnTqHApedwSnLoqvVakTtPp
