development:
  GOOGLE_CLIENT_ID: 754802324470-7poiqgk8c2j0of9mtutg5s9t7i0in6lv.apps.googleusercontent.com
  GOOGLE_SECRET_KEY: iZFvmtcQzTnm4WsRRI1uDRi8

production:
  GOOGLE_CLIENT_ID: 754802324470-f341bt2mmp7lthm56rftbc3gua304ctr.apps.googleusercontent.com
  GOOGLE_SECRET_KEY: -SnTqHApedwSnLoqvVakTtPp
